### ISSUE TITLE
searchMode: has_any on a filter config is incorrectly encoded in the API request

### ISSUE THREAD

**Issue by rdoh** [sharetribe/ftw-hourly#99] opened 2020-06-20 10:00 UTC
**Describe the bug**

It is encoded incorrectly in the API request like so: `pub_category=has_any%3Acar`

**To Reproduce** Steps to reproduce the behavior:

add `config: {searchMode: 'has_any'}` to a SelectMultipleFilter in marketplace-custom-config

if you use the filter through the UI you will see that the first selected option appears to be ignored (i.e. results that should match this option will not be returned by the API). That's because of the encoding described above.

**Comment by Gnito** [comment] 2020-06-26 11:56
I'll continue next week, but a couple of questions first:
- Yogatime doesn't have pub_category field in use. Are you referring to a field using single-enum values (like FTW-daily does) or multi-enum? Only multi-enum has these modifiers (has_any, has_all). 
  https://www.sharetribe.com/api-reference/marketplace.html#extended-data-filtering
- `%3A` is just a URL encoded version of colon character (':'). Flex API is able to decode it.

**Comment by Gnito** [comment] 2020-08-06 13:41
I wasn't able to reproduce this. My assumption is that the bug happened due to undefined or wrong schema for the particular public data key.

There hasn't been any activity for a while, so closing this for now.

**Closed by Gnito** 2020-08-06 13:41 UTC
